<?php
$this->headScript()->appendFile("https://www.amcharts.com/lib/3/amcharts.js");
$this->headScript()->appendFile("https://www.amcharts.com/lib/3/serial.js");
$this->headScript()->appendFile("https://www.amcharts.com/lib/3/plugins/export/export.min.js");
$this->headLink()->appendStylesheet("https://www.amcharts.com/lib/3/plugins/export/export.css", 'all');
$this->headScript()->appendFile("https://www.amcharts.com/lib/3/themes/light.js");

$description = "$name ($currencycode)";
$this->headTitle($description);
?>

<?php $this->headStyle()->captureStart() ?>
#chartdiv {
	width	: 100%;
	height	: 500px;
}
<?php $this->headStyle()->captureEnd() ?>

<h1><?=$description?></h1>
<div id="chartdiv"></div>
<?php $this->inlineScript()->captureStart() ?>
jsonData = <?= $jsondata ?>;
<?php $this->inlineScript()->captureEnd() ?>
<?php
$this->inlineScript()->appendFile('/js/chart.js');
?>
