<?php
$title = 'Supported currencies';
$this->headTitle($title);
?>

<table class="table">
<tr>
    <th>Currency code</th>
    <th>Description</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($currencies as $currency) : ?>
    <tr>
		<td><a href="<?= $this->url(
			'exchange-rates/currency',
			['currencycode' => $currency->currencycode]
		)?>"><?= $this->escapeHtml($currency->currencycode) ?></a>
		</td>
		<td><a href="<?= $this->url(
			'exchange-rates/currency',
			['currencycode' => $currency->currencycode]
		)?>"><?= $this->escapeHtml($currency->name) ?></a>
		</td>
        <td>
<?php
?>
        </td>
    </tr>
<?php endforeach; ?>
</table>
